2022-02-18 09:46:45,197 1 INFO ? odoo: Odoo version 14.0-20220204 
2022-02-18 09:46:45,198 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2022-02-18 09:46:45,198 1 INFO ? odoo: addons paths: ['/usr/lib/python3/dist-packages/odoo/addons', '/var/lib/odoo/addons/14.0', '/mnt/extra-addons', '/opt/addons'] 
2022-02-18 09:46:45,198 1 INFO ? odoo: database: odoo@db:5432 
2022-02-18 09:46:45,369 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2022-02-18 09:46:45,485 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 2d590a2ac565:8069 
2022-02-18 09:47:16,170 1 INFO ? odoo.http: Generating nondb routing 
2022-02-18 09:47:16,191 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET / HTTP/1.1" 303 - 1 0.005 0.030
2022-02-18 09:47:16,236 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web HTTP/1.1" 303 - 2 0.011 0.024
2022-02-18 09:47:16,342 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/database/selector HTTP/1.1" 200 - 2 0.005 0.096
2022-02-18 09:47:16,474 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/fontawesome/css/font-awesome.css HTTP/1.1" 404 - 1 0.004 0.045
2022-02-18 09:47:16,490 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/css/bootstrap.css HTTP/1.1" 404 - 1 0.005 0.062
2022-02-18 09:47:16,489 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/popper/popper.js HTTP/1.1" 404 - 1 0.006 0.055
2022-02-18 09:47:16,490 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/index.js HTTP/1.1" 404 - 1 0.004 0.057
2022-02-18 09:47:16,477 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/jquery/jquery.js HTTP/1.1" 404 - 1 0.003 0.047
2022-02-18 09:47:16,506 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/util.js HTTP/1.1" 404 - 1 0.027 0.049
2022-02-18 09:47:16,602 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/alert.js HTTP/1.1" 404 - 1 0.009 0.056
2022-02-18 09:47:16,604 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/dropdown.js HTTP/1.1" 404 - 1 0.010 0.052
2022-02-18 09:47:16,621 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/modal.js HTTP/1.1" 404 - 1 0.005 0.072
2022-02-18 09:47:16,623 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/carousel.js HTTP/1.1" 404 - 1 0.002 0.074
2022-02-18 09:47:16,624 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/collapse.js HTTP/1.1" 404 - 1 0.003 0.076
2022-02-18 09:47:16,647 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/button.js HTTP/1.1" 404 - 1 0.017 0.088
2022-02-18 09:47:16,686 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/tooltip.js HTTP/1.1" 404 - 1 0.009 0.063
2022-02-18 09:47:16,699 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/popover.js HTTP/1.1" 404 - 1 0.004 0.062
2022-02-18 09:47:16,706 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/tab.js HTTP/1.1" 404 - 1 0.013 0.049
2022-02-18 09:47:16,707 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/scrollspy.js HTTP/1.1" 404 - 1 0.004 0.064
2022-02-18 09:47:16,709 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/popper/popper.js HTTP/1.1" 404 - 1 0.006 0.040
2022-02-18 09:47:16,747 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/src/img/logo2.png HTTP/1.1" 404 - 1 0.009 0.010
2022-02-18 09:47:16,751 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/index.js HTTP/1.1" 404 - 1 0.005 0.016
2022-02-18 09:47:16,771 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/util.js HTTP/1.1" 404 - 1 0.002 0.007
2022-02-18 09:47:16,799 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/alert.js HTTP/1.1" 404 - 1 0.004 0.011
2022-02-18 09:47:16,827 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/button.js HTTP/1.1" 404 - 1 0.002 0.006
2022-02-18 09:47:16,848 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/carousel.js HTTP/1.1" 404 - 1 0.003 0.007
2022-02-18 09:47:16,871 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/collapse.js HTTP/1.1" 404 - 1 0.002 0.008
2022-02-18 09:47:16,898 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/dropdown.js HTTP/1.1" 404 - 1 0.007 0.012
2022-02-18 09:47:16,917 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/modal.js HTTP/1.1" 404 - 1 0.002 0.009
2022-02-18 09:47:16,934 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/tooltip.js HTTP/1.1" 404 - 1 0.002 0.008
2022-02-18 09:47:16,955 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/popover.js HTTP/1.1" 404 - 1 0.003 0.008
2022-02-18 09:47:16,976 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/scrollspy.js HTTP/1.1" 404 - 1 0.002 0.009
2022-02-18 09:47:16,995 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:16] "GET /web/static/lib/bootstrap/js/tab.js HTTP/1.1" 404 - 1 0.002 0.008
2022-02-18 09:47:17,208 1 INFO ? werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:17] "GET /web/static/src/img/favicon.ico HTTP/1.1" 404 - 1 0.002 0.008
ERROR: couldn't write the config file
2022-02-18 09:47:50,171 1 INFO None odoo.service.db: Create database `ridha`. 
2022-02-18 09:47:50,426 1 ERROR None odoo.service.db: CREATE DATABASE failed: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 59, in _initialize_db
    odoo.modules.db.initialize(cr)
  File "/usr/lib/python3/dist-packages/odoo/modules/db.py", line 34, in initialize
    for i in odoo.modules.get_modules():
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 424, in get_modules
    plist.extend(listdir(ad))
  File "/usr/lib/python3/dist-packages/odoo/modules/module.py", line 418, in listdir
    for it in os.listdir(dir)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/addons'
2022-02-18 09:47:50,443 1 ERROR None odoo.modules.loading: Database ridha not initialized, you can force it with `-i base` 
2022-02-18 09:47:50,491 1 INFO ridha odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'user=odoo password=xxx dbname=ridha host=db port=5432 sslmode=prefer' 
2022-02-18 09:47:50,497 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:50] "POST /web/database/create HTTP/1.1" 200 - 15 0.241 0.222
2022-02-18 09:47:50,578 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:50] "GET /web/static/lib/fontawesome/css/font-awesome.css HTTP/1.1" 500 - 2 0.006 0.032
2022-02-18 09:47:50,582 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:50,698 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:50] "GET /web/static/lib/bootstrap/css/bootstrap.css HTTP/1.1" 500 - 2 0.011 0.110
2022-02-18 09:47:50,704 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:50] "GET /web/static/lib/popper/popper.js HTTP/1.1" 500 - 2 0.011 0.096
2022-02-18 09:47:50,706 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:50] "GET /web/static/lib/jquery/jquery.js HTTP/1.1" 500 - 2 0.018 0.104
2022-02-18 09:47:50,717 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:50] "GET /web/static/lib/bootstrap/js/index.js HTTP/1.1" 500 - 2 0.019 0.092
2022-02-18 09:47:50,728 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:50,731 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:50,739 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:50,748 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:50] "GET /web/static/lib/bootstrap/js/util.js HTTP/1.1" 500 - 2 0.017 0.125
2022-02-18 09:47:50,744 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:50,784 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:50,791 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:50] "GET /web/static/lib/bootstrap/js/alert.js HTTP/1.1" 500 - 2 0.057 0.134
2022-02-18 09:47:50,799 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:50,856 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:50] "GET /web/static/lib/bootstrap/js/carousel.js HTTP/1.1" 500 - 2 0.008 0.089
2022-02-18 09:47:50,859 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:50] "GET /web/static/lib/bootstrap/js/button.js HTTP/1.1" 500 - 2 0.027 0.123
2022-02-18 09:47:50,868 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:50] "GET /web/static/lib/bootstrap/js/dropdown.js HTTP/1.1" 500 - 2 0.016 0.074
2022-02-18 09:47:50,875 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:50,886 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:50,890 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:50] "GET /web/static/lib/bootstrap/js/collapse.js HTTP/1.1" 500 - 2 0.016 0.102
2022-02-18 09:47:50,895 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:50,902 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:50,969 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:50] "GET /web/static/lib/bootstrap/js/tooltip.js HTTP/1.1" 500 - 2 0.064 0.103
2022-02-18 09:47:50,985 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:50] "GET /web/static/lib/bootstrap/js/modal.js HTTP/1.1" 500 - 2 0.022 0.180
2022-02-18 09:47:50,991 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:51,006 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:51] "GET /web/static/lib/bootstrap/js/popover.js HTTP/1.1" 500 - 2 0.011 0.092
2022-02-18 09:47:51,009 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:51,030 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:51,048 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:51] "GET /web/static/lib/bootstrap/js/scrollspy.js HTTP/1.1" 500 - 2 0.014 0.041
2022-02-18 09:47:51,056 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:51,057 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:51] "GET /web/static/lib/bootstrap/js/tab.js HTTP/1.1" 500 - 2 0.007 0.048
2022-02-18 09:47:51,063 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:51] "GET /web/static/lib/bootstrap/js/carousel.js HTTP/1.1" 500 - 2 0.016 0.028
2022-02-18 09:47:51,066 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:51,071 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:51,118 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:51] "GET /web/static/src/img/logo2.png HTTP/1.1" 500 - 2 0.009 0.026
2022-02-18 09:47:51,120 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:51] "GET /web/static/lib/bootstrap/js/collapse.js HTTP/1.1" 500 - 2 0.003 0.039
2022-02-18 09:47:51,125 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:51,132 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:51,167 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:51] "GET /web/static/lib/bootstrap/js/dropdown.js HTTP/1.1" 500 - 2 0.003 0.013
2022-02-18 09:47:51,170 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:51,194 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:51] "GET /web/static/lib/bootstrap/js/modal.js HTTP/1.1" 500 - 2 0.003 0.011
2022-02-18 09:47:51,197 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:51,226 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:51] "GET /web/static/lib/bootstrap/js/tooltip.js HTTP/1.1" 500 - 2 0.003 0.020
2022-02-18 09:47:51,232 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:51,261 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:51] "GET /web/static/lib/bootstrap/js/popover.js HTTP/1.1" 500 - 2 0.005 0.016
2022-02-18 09:47:51,268 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:51,293 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:51] "GET /web/static/lib/bootstrap/js/scrollspy.js HTTP/1.1" 500 - 2 0.004 0.012
2022-02-18 09:47:51,299 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:47:51,325 1 INFO ridha werkzeug: 172.21.0.1 - - [18/Feb/2022 09:47:51] "GET /web/static/lib/bootstrap/js/tab.js HTTP/1.1" 500 - 2 0.004 0.014
2022-02-18 09:47:51,329 1 ERROR ridha werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 441, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 113, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 88, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1306, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1462, in dispatch
    ir_http = request.registry['ir.http']
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'ir.http' - - -
2022-02-18 09:48:45,574 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:48:45,575 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:48:47,582 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:48:47,582 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:49:45,633 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:49:45,634 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:49:48,639 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:49:48,640 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:50:45,645 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:50:45,646 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:50:49,703 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:50:49,704 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:51:45,656 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:51:45,658 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:51:50,731 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:51:50,732 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:52:45,661 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:52:45,662 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:52:51,744 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:52:51,744 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:53:45,689 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:53:45,689 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:53:52,798 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:53:52,798 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:54:45,750 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:54:45,751 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:54:53,859 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:54:53,860 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:55:45,790 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:55:45,791 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:55:54,920 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:55:54,921 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:56:45,854 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:56:45,854 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:56:55,985 1 ERROR ridha odoo.sql_db: bad query: SELECT latest_version FROM ir_module_module WHERE name='base'
ERROR: relation "ir_module_module" does not exist
LINE 1: SELECT latest_version FROM ir_module_module WHERE name='base...
                                   ^
 
2022-02-18 09:56:55,986 1 WARNING ? odoo.addons.base.models.ir_cron: Tried to poll an undefined table on database ridha. 
2022-02-18 09:57:17,050 1 INFO ? odoo.service.server: Initiating shutdown 
2022-02-18 09:57:17,050 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
